# Spark Infrastructure Inventory
all:
  children:
    proxmox:
      hosts:
        spark-hypervisor:
          ansible_host: 192.168.1.100
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox_key

    kubernetes:
      children:
        k8s_masters:
          hosts:
            spark-conductor:-
              ansible_host: 192.168.1.101
              ansible_user: ubuntu
              kubernetes_role: master
              kubernetes_master_ip: 192.168.1.101

        k8s_workers:
          hosts:
            spark-executor-01:
              ansible_host: 192.168.1.102
              ansible_user: ubuntu
              kubernetes_role: worker
            spark-executor-02:
              ansible_host: 192.168.1.103
              ansible_user: ubuntu
              kubernetes_role: worker

    monitoring:
      hosts:
        spark-observer:
          ansible_host: 192.168.1.110
          ansible_user: ubuntu
          monitoring_role: prometheus
        spark-logger:
          ansible_host: 192.168.1.111
          ansible_user: ubuntu
          monitoring_role: elasticsearch

    development:
      hosts:
        spark-builder:
          ansible_host: 192.168.1.120
          ansible_user: ubuntu
          service_role: github_runner
        spark-registry:
          ansible_host: 192.168.1.121
          ansible_user: ubuntu
          service_role: docker_registry

  vars:
    # Global Variables
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    cluster_name: spark-cluster
    domain_name: schnebel-it.local

    # Kubernetes Configuration
    kubernetes_version: "1.28.2"
    cni_plugin: calico
    pod_network_cidr: "10.244.0.0/16"
    service_subnet: "10.96.0.0/12"

    # Monitoring Configuration
    prometheus_retention: "30d"
    grafana_admin_password: "{{ vault_grafana_password }}"

    # Security
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
