---
# Public Ingress Controller - für öffentlich erreichbare Apps
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-public
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: public
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx-public
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx-public
  valuesContent: |-
    controller:
      ingressClassResource:
        name: nginx-public
        enabled: true
        default: false
        controllerValue: "k8s.io/ingress-nginx-public"
      ingressClass: nginx-public
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.200  # Öffentliche IP
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/address-pool: public-pool
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
        server-name-hash-bucket-size: "256"
        ssl-protocols: "TLSv1.2 TLSv1.3"
        ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384"
        enable-real-ip: "true"
        proxy-real-ip-cidr: "0.0.0.0/0"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 500m
          memory: 512Mi
      nodeSelector:
        kubernetes.io/os: linux
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true
          image:
            registry: k8s.gcr.io
            image: ingress-nginx/kube-webhook-certgen
            tag: v1.3.0

---
# Internal Ingress Controller - für interne Apps (VPN-Zugriff)
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-internal
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: internal
    name: ingress-nginx-internal
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx-internal
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx-internal
  valuesContent: |-
    controller:
      ingressClassResource:
        name: nginx-internal
        enabled: true
        default: false
        controllerValue: "k8s.io/ingress-nginx-internal"
      ingressClass: nginx-internal
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.201  # Interne IP
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/address-pool: internal-pool
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
        server-name-hash-bucket-size: "256"
        ssl-protocols: "TLSv1.2 TLSv1.3"
        whitelist-source-range: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"  # Nur interne Netzwerke
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 300m
          memory: 256Mi
      nodeSelector:
        kubernetes.io/os: linux
      admissionWebhooks:
        enabled: true

---
# MetalLB IP Address Pools
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.200-192.168.1.210  # IP-Range für öffentliche Services

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.201-192.168.1.205  # IP-Range für interne Services

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - public-pool

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - internal-pool
